server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml